#!/bin/bash

##########################################################
#This is called by incrond, which passes 3 variables to it.
#
# $1 is the path to the file that was
#accessed/modified
#
# $2 is the filename
#
# $3 is the trigger that called it
#
# Example:
#       archiver ~/Documents/ importantFile.txt IN_ACCESS
#########################################################

tmp="tmp/"
bak="bak/"

if [ $3 == "IN_ACCESS" ]        #If the script was called because a file was accessed
then
        if [ ! -d $1$tmp ]      #If the tmp directory doesn't exist
        then
                mkdir $1$tmp    #Make it
        fi

        cp "$1$2" "$1$tmp$2"    #Put a copy of the original in that directory's tmp folder
        logger $?               #Log success/failure of the copy
        logger $1$2             #Log the source path/filename
        logger $1$tmp$2         #Log the desitination path/filename
elif [ $3 == "IN_MODIFY" ]      #Otherwise if the script was called because the file as modifiesd
then
        if [ ! -d $1$bak ]      #If the bak directory doesn't exist
        then
                mkdir $1$bak    #Make it
        fi

        cp "$1$tmp$2" "$1$bak$2-$(date +'%m-%d-%y-%T')" #Copy the temporary file to the bak folder
        logger $?                                       #Log success/failure of the copy
        if [ $? == 0 ]                                  #If the copy succeeds
        then
                rm "$1$tmp$2"                           #Remove the copy from the tmp folder
                logger $?                               #Log success or failure of the remove
                logger $1$tmp$2                         #Log the source path/filename
                logger $1$bak$2                         #Log the destination path/filename
        fi
fi
